### ISSUE TITLE
Can't see weather effects with version 0.3.0

### ISSUE THREAD

**Issue by DiegoAAG-aoe** [AndreyMrovol/LethalWeatherRegistry#10]
i just updated the  WeatherRegistry mod and i notice that  weather like rainy or flooded had no effects, and deactivating and activating mods from my modpack I realized that the last version of this mod was the problem, so I downgraded to version 0.2.9 and everything worked perfect regarding the weather effects.

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue! I've just pushed v0.3.1, which should resolve this issue - please let me know if it does!

**Comment by DiegoAAG-aoe** [comment]
its fixed now! thx
