### ISSUE TITLE
(BUG) multiple weathers at once everyday

### ISSUE THREAD

**Issue by TheComicRelief** [AndreyMrovol/LethalWeatherRegistry#12]
Since last update, every time I go on a moon with rainy, eclipsed or stormy, I always have all of them at once. Disabling the mod and mods using this mod fixes it.
my code: 01937fef-aecb-c462-f9fb-acd225739747

**Comment by TheComicRelief** [comment]
The weathers appear all at once then after some time on a moon, it fixes itself to the original weather.

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - please check if latest version (v0.3.4) fixes this issue 😅

**Comment by TheComicRelief** [comment]
It works fine now. Thanks 👍
