### ISSUE TITLE
(BUG) scrap multiplier setting keeps reverting back to false

### ISSUE THREAD

**Issue by TheComicRelief** [AndreyMrovol/LethalWeatherRegistry#13]
The scrap multiplier resets to false every time I pull the level.
my modpack code: 0193aa8e-2b6a-ed88-2b32-2d0bf4b4b98f

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - this is done **purposefully** by `CentralConfig`:

https://github.com/ImpulsiveLad/CentralConfig/blob/15d6ed70c5d74c4404351cb6a9e37bf78edb959c/CentralConfig/Compat.cs#L36-L40

I understand that this reduces the user experience, but you'd have to [talk to CentralConfig dev](https://discord.com/channels/1168655651455639582/1243711422597173268) or [report an issue in their repo](https://github.com/ImpulsiveLad/CentralConfig/issues) for a fix.
