### ISSUE TITLE
(BUG (possibly)) Weather condition displaying on monitor despite being disabled

### ISSUE THREAD

**Issue by LONINFINITY** [AndreyMrovol/LethalWeatherRegistry#14]
With coloured weather on the monitors disabled, Weather Registry is still overriding the monitor and displaying the weather, even with mods such as "UnknownWeather" installed which are meant to entirely hide weather. While I'm sure this is a nice feature for some people, it makes it difficult to entirely hide the weather, and it would be nice if this was either limited _only_ to having coloured weather enabled, or for it to be a separate config entry on its own, so as to hide weather on the main monitor.

**Comment by AndreyMrovol** [comment]
Hey, the `Colored Weathers` option is only applying to colors, not the whole patch 😅 - I'll try to think if there's a better way to handle this.

> even with mods such as "UnknownWeather" installed which are meant to entirely hide weather
I would recommend you [WeatherTweaks](https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaksExperimental/) mod, which - among other things - has "AlwaysUnknown" option that works like `UnknownWeather` mod.

**Comment by LONINFINITY** [comment]
> I would recommend you [WeatherTweaks](https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaksExperimental/) mod, which - among other things - has "AlwaysUnknown" option that works like UnknownWeather mod.

I appreciate the recommendation, though unfortunately WeatherTweaks' "AlwaysUnknown" option doesn't hide the monitor listing either, and isn't compatible with mods that add new weather conditions such as [LethalElements](https://thunderstore.io/c/lethal-company/p/v0xx/LethalElements/).

**Comment by AndreyMrovol** [comment]
yeah, that's my fault for not updating the mod enough 😅

have you tried https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaksExperimental/ ?

**Comment by LONINFINITY** [comment]
I've just tried it now and it also seems unable to hide the monitor's weather listing, though there's a possibility that the experimental version is incompatible with something else I'm using as the config seems only half-generated or incomplete. The config makes no mention of the progressing weather, for instance.

**Comment by AndreyMrovol** [comment]
> I've just tried it now and it also seems unable to hide the monitor's weather listing

That's really interesting, could you send me a screenshot of _what you mean_ (since I'm pretty sure i misunderstood you) and your modpack code?


> The config makes no mention of the progressing weather, for instance.

Those config entries have been moved to WeatherRegistry's config.

**Comment by LONINFINITY** [comment]
Ah my mistake, I just assumed that WeatherTweaks would have the config for the things listed on the mod page for it.
![image](https://github.com/user-attachments/assets/9a2409e4-62fa-4b4a-bae7-7e80f286c395)

This weather listing here is what I mean, and while the modpack code is `0193b0b8-b9d4-fc2e-ccc6-98de3214b000`, I believe this behavior occurs even when the only mods installed are WeatherRegistry and UnknownWeather (though I'll just double check that to be certain)

**Comment by AndreyMrovol** [comment]
Could you check if toggling `AlwaysUnknown` in WeatherTweaks config hides it?

**Comment by AndreyMrovol** [comment]
> It is actually displaying [UNKNOWN] now rather than specific weather

Yeah, that's how WeatherTweaks displays it - it's fully compatible with WeatherRegistry (and - by extension - all modded weathers) 😅

> that shows that it's conflicting with another mod I've got on the full-scale pack

If you mean the incompatibility between UnknownWeathers and WeatherRegistry - there's no solution to this _right now_, since Registry completely overrides the ship display.

**Comment by LONINFINITY** [comment]
I was under the impression that WeatherTweaks changed weather to work on a weight system, and the absence of LethalElements' conditions in the config led me to believe it may just exclude them entirely, which I guess is what I get for making assumptions 😅

> If you mean the incompatibility between UnknownWeathers and WeatherRegistry - there's no solution to this right now, since Registry completely overrides the ship display.

This is pretty much the main issue, that Registry is overriding the ship display when it isn't necessarily doing anything with weather colours disabled

**Comment by AndreyMrovol** [comment]
> I was under the impression that WeatherTweaks changed weather to work on a weight system

Yeah, WeatherRegistry split off from WeatherTweaks at some point, and - in case of "normal" Tweaks version - I've still not managed to update everything so there's no feature overlap 🥲

> This is pretty much the main issue, that Registry is overriding the ship display when it isn't necessarily doing anything with weather colours disabled

It still _reorganizes_ the layout of ship screen: in vanilla weathers are at the very bottom (not ideal); also the "old" weather-related mods were made long before Registry was a thing, and I've tried (with varying degrees of success) to include compability/replacements of their functionality (such as :
1.UnknownWeathers being part of WeatherTweaks
2. weather-weather weights being a part of WeatherTweaks at some point
3. weather scrap multipliers are part of Registry)
and more I can't remember right now 😅

So yeah, the incompatibility is unfortunate, but - at least in my opinion - keeping compatibility with 11-month old mods while I offer **more functionality** in my own mods is not the way I want to go 🥺

**Comment by LONINFINITY** [comment]
That's sensible I suppose - I didn't realise that WeatherTweaks was intended to assume the functionality of UnknownWeather entirely. In that case, could you clear up whether or not WeatherTweaks messes with custom weather like LethalElements? Or would they be compatible?

As for the hidden weather on the monitor part, I suppose I should just make a feature request on Weather Tweaks Experimental in particular to hide the line instead of displaying [unknown], rather than here 😅 although I'm curious, is it possible to disable the weather->weather weights on weathertweaks?

**Comment by LONINFINITY** [comment]
I appreciate you humouring my nonsensical rambling 🙏 I suppose I'll have to look further into what breaks weathertweaks' monitor change on my larger modpack then
