### ISSUE TITLE
[Issue] won't get new weather RNG after get fired, and some issue about weathertweak new weather call `blackout`

### ISSUE THREAD

**Issue by CoolLKKPS** [AndreyMrovol/LethalWeatherRegistry#15]
first issue is exactly the same as topic
about weathertweak new weather, actually it throw error at the beginning when i just start launching the game
@AndreyMrovol pls pls pls fix that...

**Comment by CoolLKKPS** [comment]
ok EVEN CAUSE DE-SYNC

**Comment by AndreyMrovol** [comment]
I've released v0.3.7, please check if it fixes your issue.

**Comment by CoolLKKPS** [comment]
will open in another issue ticket
