### ISSUE TITLE
[Issue] Scrap multiplier cannot disabled

### ISSUE THREAD

**Issue by CoolLKKPS** [AndreyMrovol/LethalWeatherRegistry#16]
@AndreyMrovol same as topic

**Comment by CoolLKKPS** [comment]
i have weathertweak and this mod

**Comment by AndreyMrovol** [comment]
Please explain a bit more - when does it happen? What's the issue?

**Comment by CoolLKKPS** [comment]
a bit lazy bc i were done too much things today, in short, scrap value and amount will always be multiplied

**Comment by CoolLKKPS** [comment]
i more sus this cause by beta weathertweak but idk
