### ISSUE TITLE
(BUG?) Possible terminal bug?

### ISSUE THREAD

**Issue by TheComicRelief** [AndreyMrovol/LethalWeatherRegistry#2]
Idk if this is the cause but it has happened since this mod appears when updating weathertweaks. The bug causes me to not lock in the terminal making you glitch out of the ship at times when exiting the terminal. Here's the code for my modpack: 018ffc78-e404-3cbc-1e40-25fb2a04b37d.

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - I'll get back to you after testing this properly.
