### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by MathiusXII** [AndreyMrovol/LethalWeatherRegistry#3]
Are these config entries correct?
It seems like all the weathers have the same chance but I've configged them with different chances 
Also I don't understand what "Weather weights" is supposed to do. 

```

[Weather: DustClouds]

## The default weight of this weather
# Setting type: Int32
# Default value: 100
# Acceptable value range: From 0 to 10000
Default weight = 100

## Multiplier for the amount of scrap spawned
# Setting type: Single
# Default value: 1
# Acceptable value range: From 0 to 100
Scrap amount multiplier = 1.0

## Multiplier for the value of scrap spawned
# Setting type: Single
# Default value: 1
# Acceptable value range: From 0 to 100
Scrap value multiplier = 1

## Whether to make the filter a whitelist (false is blacklist, true is whitelist)
# Setting type: Boolean
# Default value: false
Filtering option = true

## Semicolon-separated list of level names to filter
# Setting type: String
# Default value: Gordion;
Level filter = Assurance;Experimentation;Offense;Artifice;Embrion

## Semicolon-separated list of level weights
# Setting type: String
# Default value: LevelName@Weight;
Level weights = Assurance@100;Experimentation@100;Offense@100;Artifice@30;Embrion@50

## Semicolon-separated list of weather weights
# Setting type: String
# Default value: WeatherName@Weight;
Weather weights = 

```

**Comment by AndreyMrovol** [comment]
Hey, every weather has 3 weights that can be used:

1. Level weight - this weight is used **on the specific level**, for example `Vow@200` would make Vow have 200 weight for given weather 
2. WeatherToWeatherWeight - this is the weight that is applied **when the provided weather is the previous day weather** on a given moon, so `Foggy@150` would set the weather's weight to 150 **when there was a Foggy weather** on the previous day
3. Default weight - this is applied when conditions (1) and (2) cannot be used (so _a default_)

Right now the (1) and (2) are not used in code, but that's gonna be changed today/tomorrow

**Comment by MathiusXII** [comment]
@AndreyMrovol Thanks. Do you know what the default chances are? That'd help me a lot
