### ISSUE TITLE
[Bug] Apparatus value doesn't scale with weather multipliers when set via FacilityMeltdown

### ISSUE THREAD

**Issue by ajsglist** [AndreyMrovol/LethalWeatherRegistry#6]
Hey there,

When the apparatus value is set via FacilityMeltdown, weather multipliers do not change the value like other loot.

I'm not sure which mod would be better suited to handle the issue, so I've posted in both githubs and will link them for convenience.

Thanks :)

ref: https://github.com/LoafOrc/FacilityMeltdown/issues/50

**Comment by AndreyMrovol** [comment]
Hey, thanks for your report - I haven't implemented apparatus value changes, I'll try to get it done 😅

**Comment by ajsglist** [comment]
I haven't had time to test, but LoafOrc says this should be fixed on their end now.  Will reopen ticket if I notice any issues when I finally get back into updating the pack.

Thanks again for your work on WeatherRegistry
