### ISSUE TITLE
Scrap value bugged

### ISSUE THREAD

**Issue by JonasMush** [AndreyMrovol/LethalWeatherRegistry#8]
Hello, I have an issue and I seem to have trouble with it.

I added weatheregistry in a modpack I use to play Lethal Company. Everything works, until I noticed something off. The scrap value (which in the config files is defaulted to 1) seems to make scrap cheaper then it's supposed to be.
For example: a tattered metal sheet's min value is 10 and it's max is 22, but when I found it while using this mod, it showed that it was worth a measly 2 credits. Bumping the scrap value multiplier to 2 solves the issue, but I don't think this is intended right? Why would the default value cause scrap to be less expensive? I mean, it's easily solvable by just changing every single value multiplier to 2, but I still found it odd so wrote it down here. 

I am sure this mod was the cause as well, because I disabled mods 1 by 1 trying to find which mod was causing this scrap value loss and it turned out to be weather registry. If anyone could tell me why this happens that would be appreciated. (Also excuse me if I'm not that educated on the whole modding side of things, I wish I were more knowledged in that department)

**Comment by AndreyMrovol** [comment]
Hey, thanks for the find, that's really interesting. Are you using latest version of Registry? Is it happening on version before (0.1.23)?

**Comment by AndreyMrovol** [comment]
Hey, please let me know if the latest version (0.1.25) fixes your issue.

**Comment by JonasMush** [comment]
I will check it out, will post it here if it worked, thx for the fast reply :D

**Comment by JonasMush** [comment]
Side note: It does occur on version 0.1.24

**Comment by JonasMush** [comment]
Update: 0.1.25 has fixed this issue, thank you so much for the quick patch, truly a developer with a love for his hobbies and an awesome member of the modding community!
